export enum UserRole {
  CHAIRPERSON = 'CHAIRPERSON',
  EXECUTIVE = 'EXECUTIVE',
  NON_EXECUTIVE = 'NON_EXECUTIVE',
  SECRETARY = 'SECRETARY'
}

export enum MeetingStatus {
  SCHEDULED = 'SCHEDULED',
  LIVE = 'LIVE',
  IN_CAMERA = 'IN_CAMERA',
  CLOSED = 'CLOSED'
}

export enum ActionStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  OVERDUE = 'OVERDUE'
}

export enum VoteType {
  FOR = 'FOR',
  AGAINST = 'AGAINST',
  ABSTAIN = 'ABSTAIN'
}

export type UserStatus = 'ACTIVE' | 'PENDING_APPROVAL' | 'PENDING_TERMINATION' | 'TERMINATED' | 'FROZEN';

export interface User {
  id: string;
  name: string;
  role: UserRole;
  avatar: string;
  initials: string;
  status: UserStatus;
  approvals: string[]; // IDs of board members who approved onboarding
  terminationApprovals?: string[]; // IDs of board members who approved termination
  terminationReason?: string; // Reason for termination request
  passwordResetRequest?: {
    requestedBy: string; // User ID (usually Secretary)
    newTempPassword?: string; // Stored temporarily for demo purposes
    approvals: string[]; // IDs of directors who approved the change
    reason: string;
  };
  documents?: {
    certifiedId: boolean;
    proofOfResidence: boolean;
    cv: boolean;
  };
  email?: string;
}

export interface AgendaItem {
  id: string;
  title: string;
  presenter: string;
  durationMinutes: number;
  isComplianceCheck: boolean; // e.g., B-BBEE, Conflict of Interest
  documents: string[];
  aiNotes?: string; // Generated by Gemini
}

export interface ActionItem {
  id: string;
  task: string;
  owner: string; // User Name
  deadline: string;
  status: ActionStatus;
  source: 'Meeting' | 'Email' | 'WhatsApp';
  lastUpdate?: string;
  pendingEdit?: {
    requestedBy: string;
    approvals: string[];
    newStatus?: ActionStatus;
    newTask?: string;
    newDeadline?: string;
    newOwner?: string;
  };
}

export interface Meeting {
  id: string;
  title: string;
  date: string;
  status: MeetingStatus;
  location: string;
  agenda: AgendaItem[];
  complianceScore?: number; // 0-100
}

export interface VoteEvent {
  id: string;
  agendaItemId: string;
  question: string;
  isOpen: boolean;
  votes: Record<string, VoteType>; // UserId -> VoteType
}

export interface AuditLogEntry {
  id: string;
  timestamp: string;
  userId: string;
  userName: string;
  action: string;
  details: string;
  ipHash?: string; // Simulated for visual effect
}

export type DocType = 'MINUTES' | 'PACK' | 'POLICY' | 'FINANCIALS';

export interface RepositoryDoc {
  id: string;
  title: string;
  type: DocType;
  date: string;
  size: string;
  uploadedBy: string;
  pendingDeletion?: {
    requestedBy: string; // User ID
    approvals: string[]; // Array of User IDs who approved
  };
}